name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { project: 'actix-example', target: 'x86_64' }
          - { project: 'actix-example', target: 'aarch64' }
          - { project: 'axum-example', target: 'x86_64' }
          - { project: 'axum-example', target: 'aarch64' }
          - { project: 'rocket-example', target: 'x86_64' }
          - { project: 'rocket-example', target: 'aarch64' }

    steps:
    - name: Update Rust toolchain
      run: rustup update
    - name: Update Rust toolchain
      run: rustup target add ${{ matrix.config.target }}-unknown-linux-gnu
    - name: Install cross
      run: cargo install cross
    - uses: actions/checkout@v5
    - name: Build
      working-directory: ${{ matrix.config.project }}
      run: cross build --target=${{ matrix.config.target }}-unknown-linux-gnu
