name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { project: 'actix-example' }
          - { project: 'axum-example' }
          - { project: 'rocket-example' }

    steps:
    - name: Update Rust toolchain
      run: rustup update
    - uses: actions/checkout@v4
    - name: Build
      working-directory: ${{ matrix.config.project }}
      run: cargo build
